{"uuid": "b6db3a48-20ac-4d68-9074-bbbee77aff42", "children": ["35122159-8efd-4ea3-becc-080ede6752fc"], "befores": [{"name": "set_up_test", "status": "passed", "start": 1552187561328, "stop": 1552187576754}], "afters": [{"name": "set_up_test::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=72.0.3626.121)\n  (Driver info: chromedriver=73.0.3683.20 (8e2b610813e167eee3619ac4ce6e42e3ec622017),platform=Windows NT 10.0.17134 x86_64)\n\n", "trace": "  File \"C:\\Users\\PriyaPramod\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\allure_commons\\_allure.py\", line 169, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\PriyaPramod\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 796, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\Development\\Amazon\\conftest.py\", line 32, in set_up_test\n    helpers.attach_screen_shot(driver, request.function.__name__)\n  File \"D:\\Development\\Amazon\\source\\utilities\\helpers.py\", line 20, in attach_screen_shot\n    allure.attach(driver.get_screenshot_as_png(), name,\n  File \"C:\\Users\\PriyaPramod\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 195, in _wrap\n    self._listener.on_exception(e, self._driver)\n  File \"D:\\Development\\Amazon\\source\\utilities\\listeners.py\", line 19, in on_exception\n    helpers.attach_screen_shot(driver, exception)\n  File \"D:\\Development\\Amazon\\source\\utilities\\helpers.py\", line 20, in attach_screen_shot\n    allure.attach(driver.get_screenshot_as_png(), name,\n  File \"C:\\Users\\PriyaPramod\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1064, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"C:\\Users\\PriyaPramod\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1074, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"C:\\Users\\PriyaPramod\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\PriyaPramod\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1552187603714, "stop": 1552187603763}], "start": 1552187561328, "stop": 1552187603763}